# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 5.0.x
      -name: Restore dependencies
       run: dotnet restore
      -name: Build
        run: dotnel build --no-restore
      -name: Test
        run:dotnet Test
     
        
